name: Log AQI Surabaya per jam

on:
  schedule:
    - cron: '0 * * * *'  # Setiap jam
  workflow_dispatch:     # Bisa dijalankan manual juga

jobs:
  log-aqi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Jalankan script logging
        run: |
          echo "Menjalankan log_aqi.py..."
          python log_aqi.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Setup GitHub credentials
        run: git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit hasil ke repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add aqi_log.csv
          git commit -m "Update AQI log $(date)" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

