name: Log AQI Surabaya per jam

on:
  schedule:
    - cron: '0 * * * *'  # ini artinya setiap 30 menit
  workflow_dispatch:

jobs:
  log-aqi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run AQI logger
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: python log_aqi.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add aqi_log.csv
        git commit -m "Update AQI log $(date -u)"
        git push
